language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install gnupg
python:
  - "2.7"
  - "3.4"
install:
  - pip install coveralls
  - make install
script:
  - make test
after_success:
  coveralls
